# Generated by Django 4.1.3 on 2023-04-08 19:25

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="",
                max_length=50,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_lowercased_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_lowercased_username",
            ),
        ),
    ]
